-- SUPABASE DATABASE SETUP SCRIPT (Game Hub v1.0)
-- Copy and run this script in the Supabase SQL Editor to initialize your database.

-- 0. Enable pg_graphql extension
CREATE EXTENSION IF NOT EXISTS pg_graphql;

-- 1. Create Profiles Table (Linked to Supabase auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  username TEXT,
  avatar_url TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security (RLS) for profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles
  FOR SELECT USING (true);

CREATE POLICY "Users can update their own profile" ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

-- Trigger to automatically create a profile record when a new user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username, avatar_url)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'username', NEW.email),
    NEW.raw_user_meta_data->>'avatar_url'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- 2. Create Games Table
CREATE TABLE IF NOT EXISTS public.games (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL,
  category TEXT NOT NULL,
  difficulty TEXT NOT NULL, -- 'Easy' | 'Medium' | 'Hard'
  rating NUMERIC DEFAULT 4.5 NOT NULL,
  plays INTEGER DEFAULT 0 NOT NULL,
  thumbnail_url TEXT,
  iframe_url TEXT,
  controls_json JSONB DEFAULT '{}'::jsonb NOT NULL,
  rules_json JSONB DEFAULT '[]'::jsonb NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for games
ALTER TABLE public.games ENABLE ROW LEVEL SECURITY;

-- Games Policies
CREATE POLICY "Games are viewable by everyone" ON public.games
  FOR SELECT USING (true);

CREATE POLICY "Authenticated/Service users can modify games" ON public.games
  FOR ALL USING (true) WITH CHECK (true);


-- 3. Create User Games Table (Library)
CREATE TABLE IF NOT EXISTS public.user_games (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  game_id BIGINT REFERENCES public.games(id) ON DELETE CASCADE NOT NULL,
  saved_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  UNIQUE (user_id, game_id)
);

-- Enable RLS for library
ALTER TABLE public.user_games ENABLE ROW LEVEL SECURITY;

-- User Games Policies
CREATE POLICY "Users can view their own library entries" ON public.user_games
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own library entries" ON public.user_games
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own library entries" ON public.user_games
  FOR DELETE USING (auth.uid() = user_id);


-- 4. Create Game Analytics Table (Telemetry & High Scores)
CREATE TABLE IF NOT EXISTS public.game_analytics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id BIGINT REFERENCES public.games(id) ON DELETE CASCADE NOT NULL,
  session_id TEXT NOT NULL,
  duration_seconds INTEGER NOT NULL,
  completed BOOLEAN DEFAULT false NOT NULL,
  score INTEGER,
  player_name TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for game analytics
ALTER TABLE public.game_analytics ENABLE ROW LEVEL SECURITY;

-- Game Analytics Policies
CREATE POLICY "Scores and sessions are viewable by everyone" ON public.game_analytics
  FOR SELECT USING (true);

-- Allow both anonymous/auth runs to log telemetry / submit scores
CREATE POLICY "Anyone can log telemetry" ON public.game_analytics
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Anyone can update telemetry sessions" ON public.game_analytics
  FOR UPDATE USING (true) WITH CHECK (true);


-- 5. Seed Games Catalog
INSERT INTO public.games (id, title, slug, description, category, difficulty, rating, plays, thumbnail_url, iframe_url, controls_json, rules_json)
VALUES
  (1, 'Snake', 'snake', 'The retro block-eating serpent returns. Remastered with modern visuals, fluid keyboard controls, and local high scores. Navigate the field, eat food, and grow longer without crashing into the walls or your own tail.', 'Arcade', 'Easy', 4.8, 14820, '', '/games/snake/embed', '{"movement": "Arrow Keys / WASD", "pause": "P key", "restart": "R key"}'::jsonb, '["Navigate the snake to eat glowing red food pellets.", "Each food pellet increases your length and speeds up the game.", "Game over if you collide with the border walls or your own body."]'::jsonb),
  (2, 'Pong', 'pong', 'Experience the granddaddy of arcade games. Take control of your paddle and bounce the ball past your opponent. Play against a challenging local AI and claim retro table-tennis glory.', 'Retro', 'Easy', 4.5, 8900, '', '/games/pong/embed', '{"player 1 (Left)": "W / S keys", "player 2 (Right)": "Arrow Up / Down keys", "pause": "P key"}'::jsonb, '["Bounce the ball back and forth using your paddles.", "Score a point when the ball passes the opponent''s screen edge.", "The first player to score 11 points wins the match."]'::jsonb),
  (3, 'Tetris', 'tetris', 'The ultimate block-fitting puzzle classic. Rotate, shift, and drop falling tetrominoes to clear complete horizontal lines. Manage speed tiers as the board fills up rapidly.', 'Puzzle', 'Medium', 4.9, 23150, '', '/games/tetris/embed', '{"move": "Left / Right Arrows", "rotate": "Up Arrow / X key", "soft drop": "Down Arrow", "hard drop": "Spacebar", "hold": "C key / Shift"}'::jsonb, '["Arrange falling puzzle blocks to form complete horizontal lines.", "Completed lines are cleared and award score multipliers.", "Game ends immediately when blocks stack up to the top of the grid."]'::jsonb),
  (4, 'Flappy Bird', 'flappy-bird', 'Tap to flap and navigate through narrow green pipe structures. Fluid physics, timing-based jumps, and high-difficulty scrolling challenges will test your absolute reflexes.', 'Arcade', 'Medium', 4.6, 16200, '', '/games/flappy-bird/embed', '{"flap": "Spacebar / Left Mouse Click", "pause": "P key"}'::jsonb, '["Tap flap controls to keep the bird flying upwards.", "Avoid colliding with the floating green pipes or the ground.", "Score one point for every set of pipes successfully navigated."]'::jsonb),
  (5, 'Breakout', 'breakout', 'Retro brick-breaker action. Control a sliding paddle to keep a bouncing ball in play, shattering rows of colorful neon bricks with distinct power-ups and physics calculations.', 'Arcade', 'Medium', 4.7, 12050, '', '/games/breakout/embed', '{"move": "Left / Right Arrows or Mouse Move", "release": "Spacebar / Left Click"}'::jsonb, '["Destroy all bricks on the top board to clear the level.", "Keep the ball in play by deflecting it with your paddle.", "Losing all lives causes a game over."]'::jsonb),
  (6, 'Asteroids', 'asteroids', 'Pilot your spacecraft in a chaotic asteroid field. Thrust through weightless space, rotate, and blast giant space rocks into smaller fragments while avoiding screen-wrapping collisions.', 'Action', 'Hard', 4.8, 19400, '', '/games/asteroids/embed', '{"rotate": "Left / Right Arrows", "thrust": "Up Arrow", "shoot": "Spacebar", "hyperspace": "Shift key"}'::jsonb, '["Shoot asteroids to break them down and score points.", "Dodge moving debris and alien saucers that shoot back.", "Crashing into any object destroys your ship and costs a life."]'::jsonb),
  (7, 'Space Invaders', 'space-invaders', 'Defend Earth against descending grids of alien invaders. Take cover behind bunkers and take out the alien columns before they reach the ground level.', 'Retro', 'Hard', 4.8, 15600, '', '/games/space-invaders/embed', '{"move": "Left / Right Arrow keys", "shoot": "Spacebar"}'::jsonb, '["Eliminate all aliens in the grid to secure the stage.", "Use shielding bunkers to take cover from incoming alien fire.", "If any alien invader reaches the bottom line, it''s instant game over."]'::jsonb),
  (8, 'Pac-Man Style', 'pacman', 'A legendary maze-chase experience. Gobble up yellow dots in a neon maze while escaping from four colorful ghosts with unique tracking behaviors.', 'Retro', 'Hard', 4.7, 21100, '', '/games/pacman/embed', '{"navigate": "Arrow Keys / WASD"}'::jsonb, '["Eat all pellets in the maze to complete the level.", "Avoid getting caught by the chasing ghosts.", "Eat power pellets to turn the ghosts blue and eat them for bonus scores."]'::jsonb),
  (9, 'Memory Match', 'memory-match', 'A clean card-matching brain puzzle. Flip tiles to reveal hidden neon glyphs and pair them up in as few moves as possible. Improves focus and cognitive recall.', 'Puzzle', 'Easy', 4.4, 9400, '', '/games/memory-match/embed', '{"select": "Left Mouse Click"}'::jsonb, '["Flip two cards face up at a time.", "If the icons match, the cards remain face up.", "Clear the entire board in the fewest moves to set a high score."]'::jsonb),
  (10, 'Connect Four', 'connect-four', 'The classic vertical drop board game. Drop your red or yellow discs into columns to form a straight line of four before your opponent blocks you.', 'Strategy', 'Easy', 4.5, 10200, '', '/games/connect-four/embed', '{"select": "Left Mouse Click on Column"}'::jsonb, '["Players take turns dropping one colored token from the top.", "The token falls to the lowest available space in the column.", "First to connect four tokens horizontally, vertically, or diagonally wins."]'::jsonb),
  (11, 'Tic Tac Toe', 'tic-tac-toe', 'Quick classic paper-and-pencil grid game. Face off against an unbeatable AI or play locally in an elegant neon 3x3 layout.', 'Strategy', 'Easy', 4.2, 7800, '', '/games/tic-tac-toe/embed', '{"place": "Left Mouse Click on Empty Cell"}'::jsonb, '["Place your symbol (X or O) in any empty grid cell.", "Form a line of three symbols horizontally, vertically, or diagonally to win.", "If all cells are filled and no player has three in a line, the game is a draw."]'::jsonb),
  (12, '2048', '2048', 'Slide and merge sliding number blocks. When two tiles with the same number touch, they merge into one. Work your way up to the ultimate 2048 tile.', 'Puzzle', 'Medium', 4.8, 24500, '', '/games/2048/embed', '{"slide": "Arrow Keys / WASD or Swipe gestures"}'::jsonb, '["Slide the board to shift all tiles in one direction.", "Tiles with identical values merge into a single tile of their sum.", "Keep merging tiles to reach the legendary 2048 block without running out of moves."]'::jsonb),
  (13, 'Neon Snake', 'neon-snake', 'Navigate a glowing grid, gather food capsules, and watch your neon trail grow. Collect power-ups to warp time or double your points, but avoid smashing into yourself or the neon boundaries.', 'Arcade', 'Easy', 4.9, 12500, '', 'phaser://neon-snake', '{"movement": "Arrow Keys / WASD", "swipe": "Any direction (mobile)", "pause": "P key"}'::jsonb, '["Gather glowing grid cores to score points and grow longer.", "Eating glowing purple pills slows time; yellow pills double point values.", "Colliding with boundaries or your own tail terminates the run."]'::jsonb),
  (14, 'Space Defender', 'space-defender', 'Defend deep space from waves of glowing alien ships. Move your ship horizontally, collect power-ups, activate shield grids, and defeat massive boss craft spawning every 5 waves.', 'Arcade', 'Medium', 4.8, 9800, '', 'phaser://space-defender', '{"steer": "Mouse movement / Touch drag", "shields": "Spacebar / Screen tap", "pause": "P key"}'::jsonb, '["Blast alien ships before they bypass your position. Lose 1 life for every hit.", "Collect shield charges, rapid fire lasers, and bonus lives dropped by enemies.", "Survive boss assaults on every 5th wave increment."]'::jsonb),
  (15, 'Memory Matrix', 'memory-matrix', 'Exercise your cognitive memory recall. Watch a 4x4 matrix grid of glassmorphic tiles flash with vibrant neon tones and replicate the pattern exactly as shown.', 'Puzzle', 'Medium', 4.7, 7200, '', 'phaser://memory-matrix', '{"click grid": "Left mouse click / Touch tap", "toggle mode": "Menu buttons"}'::jsonb, '["Watch the grid flash sequence carefully.", "Replicate the sequence in the exact order within the time limit.", "Chaining perfect rounds increases score multipliers and sequence length."]'::jsonb)
ON CONFLICT (slug) DO UPDATE
SET title = EXCLUDED.title,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    rating = EXCLUDED.rating,
    plays = EXCLUDED.plays,
    iframe_url = EXCLUDED.iframe_url,
    controls_json = EXCLUDED.controls_json,
    rules_json = EXCLUDED.rules_json,
    updated_at = TIMEZONE('utc'::text, NOW());
