-- SUPABASE DATABASE SETUP SCRIPT (Game Hub v1.0)
-- Copy and run this script in the Supabase SQL Editor to initialize your database.

-- 0. Enable pg_graphql extension
CREATE EXTENSION IF NOT EXISTS pg_graphql;

-- 1. Create Profiles Table (Linked to Supabase auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  username TEXT,
  avatar_url TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security (RLS) for profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles
  FOR SELECT USING (true);

CREATE POLICY "Users can update their own profile" ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

-- Trigger to automatically create a profile record when a new user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username, avatar_url)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'username', NEW.email),
    NEW.raw_user_meta_data->>'avatar_url'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- 2. Create Games Table
CREATE TABLE IF NOT EXISTS public.games (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL,
  category TEXT NOT NULL,
  difficulty TEXT NOT NULL, -- 'Easy' | 'Medium' | 'Hard'
  rating NUMERIC DEFAULT 4.5 NOT NULL,
  plays INTEGER DEFAULT 0 NOT NULL,
  thumbnail_url TEXT,
  iframe_url TEXT,
  controls_json JSONB DEFAULT '{}'::jsonb NOT NULL,
  rules_json JSONB DEFAULT '[]'::jsonb NOT NULL,
  max_score INTEGER DEFAULT 100000 NOT NULL, -- ceiling enforced by RLS on score writes
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
ALTER TABLE public.games ADD COLUMN IF NOT EXISTS max_score INTEGER DEFAULT 100000 NOT NULL;

-- Enable RLS for games
ALTER TABLE public.games ENABLE ROW LEVEL SECURITY;

-- Games Policies
CREATE POLICY "Games are viewable by everyone" ON public.games
  FOR SELECT USING (true);

-- Only the play counter may change through the public API. Everything else
-- about a game is edited by the service role (which bypasses RLS) via the seed.
DROP POLICY IF EXISTS "Authenticated/Service users can modify games" ON public.games;
CREATE POLICY "Public may only bump the play counter" ON public.games
  FOR UPDATE USING (true)
  WITH CHECK (true);
-- Column-level grant enforces that: the anon role can UPDATE plays and nothing else.
REVOKE UPDATE ON public.games FROM anon, authenticated;
GRANT UPDATE (plays) ON public.games TO anon, authenticated;


-- 3. Create User Games Table (Library)
CREATE TABLE IF NOT EXISTS public.user_games (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  game_id BIGINT REFERENCES public.games(id) ON DELETE CASCADE NOT NULL,
  saved_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  UNIQUE (user_id, game_id)
);

-- Enable RLS for library
ALTER TABLE public.user_games ENABLE ROW LEVEL SECURITY;

-- User Games Policies
CREATE POLICY "Users can view their own library entries" ON public.user_games
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own library entries" ON public.user_games
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own library entries" ON public.user_games
  FOR DELETE USING (auth.uid() = user_id);


-- 4. Create Game Analytics Table (Telemetry & High Scores)
CREATE TABLE IF NOT EXISTS public.game_analytics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id BIGINT REFERENCES public.games(id) ON DELETE CASCADE NOT NULL,
  session_id TEXT NOT NULL,
  duration_seconds INTEGER NOT NULL,
  completed BOOLEAN DEFAULT false NOT NULL,
  score INTEGER,
  player_name TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS for game analytics
ALTER TABLE public.game_analytics ENABLE ROW LEVEL SECURITY;

-- Game Analytics Policies
CREATE POLICY "Scores and sessions are viewable by everyone" ON public.game_analytics
  FOR SELECT USING (true);

-- Anonymous play is supported, so inserting a telemetry row stays open.
DROP POLICY IF EXISTS "Anyone can log telemetry" ON public.game_analytics;
CREATE POLICY "Anyone can open an unscored session" ON public.game_analytics
  FOR INSERT WITH CHECK (score IS NULL AND player_name IS NULL AND completed = false);

-- A session row may only be completed once, and only while it is fresh.
--
-- The previous policy was `USING (true)`, which let any visitor holding the
-- public anon key rewrite ANY row in this table — including other players'
-- scores — straight from the browser, bypassing the API entirely. Restricting
-- updates to rows that have no score yet makes a submitted score final, and the
-- 6-hour window stops an old session id being replayed later to inject a score.
DROP POLICY IF EXISTS "Anyone can update telemetry sessions" ON public.game_analytics;
DROP POLICY IF EXISTS "Sessions can be finalised once, while recent" ON public.game_analytics;
CREATE POLICY "Sessions can be finalised once, while recent" ON public.game_analytics
  FOR UPDATE
  USING (
    score IS NULL
    AND created_at > NOW() - INTERVAL '6 hours'
  )
  WITH CHECK (
    -- A finalised row must carry a bounded score and arcade-style initials.
    -- The ceiling comes from the game itself, so a bypass that talks to
    -- Supabase directly is still capped per game, not just at a global max.
    score IS NOT NULL
    AND score >= 0
    AND score <= (SELECT g.max_score FROM public.games g WHERE g.id = game_id)
    AND player_name ~ '^[A-Z0-9]{1,3}$'
    AND completed = true
  );

-- Nobody may delete telemetry through the public API; leaderboard history is
-- append-only. Administrative cleanup runs with the service role, which bypasses RLS.
DROP POLICY IF EXISTS "No public deletes" ON public.game_analytics;
CREATE POLICY "No public deletes" ON public.game_analytics
  FOR DELETE USING (false);

-- Indexes for the leaderboard and session lookups, which are the hot paths.
CREATE INDEX IF NOT EXISTS game_analytics_leaderboard_idx
  ON public.game_analytics (game_id, score DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS game_analytics_session_idx
  ON public.game_analytics (session_id);


-- 4b. Per-game stats view: which games people start, finish, and abandon.
--
--   SELECT * FROM public.game_stats ORDER BY starts DESC;
--
-- "starts" counts sessions opened, "scored" counts sessions that ended with a
-- submitted score, and the durations come from server-measured play time.
CREATE OR REPLACE VIEW public.game_stats AS
SELECT
  g.id,
  g.slug,
  g.title,
  g.plays                                                   AS lifetime_plays,
  COUNT(a.id)                                               AS starts,
  COUNT(a.id) FILTER (WHERE a.score IS NOT NULL)            AS scored,
  ROUND(
    100.0 * COUNT(a.id) FILTER (WHERE a.score IS NOT NULL)
    / NULLIF(COUNT(a.id), 0), 1
  )                                                         AS scored_pct,
  ROUND(AVG(a.duration_seconds) FILTER (WHERE a.score IS NOT NULL))
                                                            AS avg_seconds_when_scored,
  MAX(a.score)                                              AS top_score,
  COUNT(a.id) FILTER (WHERE a.created_at > NOW() - INTERVAL '7 days')
                                                            AS starts_last_7d
FROM public.games g
LEFT JOIN public.game_analytics a ON a.game_id = g.id
GROUP BY g.id, g.slug, g.title, g.plays;

GRANT SELECT ON public.game_stats TO anon, authenticated;


-- 5. Seed Games Catalog
-- GENERATED from lib/catalog.ts by scripts/gen-seed-sql.ts. Do not edit by hand.

-- Games removed from the catalog are deleted here; their analytics rows go with
-- them (ON DELETE CASCADE) so the leaderboards and the home page stay in sync.
DELETE FROM public.games WHERE slug NOT IN ('snake', 'pong', 'tetris', 'flappy-bird', 'breakout', 'asteroids', 'space-invaders', 'pacman', '2048', 'dino', 'pen-fight');

INSERT INTO public.games (id, title, slug, description, category, difficulty, rating, plays, thumbnail_url, iframe_url, controls_json, rules_json, max_score)
VALUES
  (1, 'Snake', 'snake', 'The retro block-eating serpent, rebuilt. Eat food, grow longer, and keep clear of the walls and your own tail. Every pellet makes the snake a little faster.', 'Arcade', 'Easy', 4.8, 14820, NULL, NULL, '{"move":"Arrow keys / WASD","touch":"Swipe to turn","pause":"P or Esc"}'::jsonb, '["Eat the red pellets to score 10 points and grow one segment.","The snake speeds up with every pellet eaten.","Hitting a wall or your own body ends the run."]'::jsonb, 5000),
  (2, 'Pong', 'pong', 'The original paddle duel. Play the CPU, share a keyboard with a friend, or create a room code and play someone online. First to 11 wins.', 'Retro', 'Easy', 4.6, 11230, NULL, NULL, '{"vs CPU":"Arrow keys or W / S","2 player (left)":"W / S","2 player (right)":"Arrow Up / Down, or drag on touch","online":"Create a room, share the 4-letter code","pause":"P or Esc"}'::jsonb, '["Return the ball past your opponent to score a point.","Where the ball hits your paddle sets the angle of the return.","First player to 11 points wins the match."]'::jsonb, 1600),
  (3, 'Tetris', 'tetris', 'Stack falling tetrominoes and clear complete lines. Full SRS rotation with wall kicks and T-spins, 7-bag piece order, hold, lock delay, ghost piece and next-piece preview.', 'Puzzle', 'Medium', 4.9, 18450, NULL, NULL, '{"move":"Left / Right (hold to auto-shift)","rotate":"Up","soft drop":"Down","hard drop":"Space","hold":"C or Shift","touch":"Tap left / right thirds to move, middle to rotate","pause":"P or Esc"}'::jsonb, '["Complete a horizontal line to clear it. Clearing several at once scores more.","T-spins score extra: rotate a T into a slot so three corners are blocked.","Every 10 lines raises the level and the fall speed.","The game ends when a new piece has no room to spawn."]'::jsonb, 500000),
  (4, 'Flappy Bird', 'flappy-bird', 'Tap to flap and thread the bird through the gaps. Deceptively simple, brutally hard. The pipes speed up every five you pass.', 'Arcade', 'Medium', 4.5, 9870, NULL, NULL, '{"flap":"Space / Up / click / tap","pause":"P or Esc"}'::jsonb, '["Each pipe you pass is one point.","Touching a pipe, the ground, or the ceiling ends the run.","Pipes move faster every five points."]'::jsonb, 1000),
  (5, 'Breakout', 'breakout', 'Smash every brick with a bouncing ball. Each level adds rows and speed, and the top rows start taking two hits from level 2.', 'Arcade', 'Medium', 4.6, 8450, NULL, NULL, '{"move":"Left / Right, mouse, or drag","launch":"Space / click / tap","pause":"P or Esc"}'::jsonb, '["Bricks score 20 points; the tough ones score 10 on the first hit.","Clearing the board awards a level bonus and a faster ball.","Miss the ball three times and the game is over."]'::jsonb, 20000),
  (6, 'Asteroids', 'asteroids', 'Pilot a lone ship through a field of drifting rocks. Big asteroids split into smaller, faster ones, and every wave adds more of them.', 'Action', 'Hard', 4.7, 7620, NULL, NULL, '{"turn":"Left / Right","thrust":"Up","fire":"Space / click","touch":"Hold and drag to steer and thrust, tap to fire","pause":"P or Esc"}'::jsonb, '["Large rocks are 20 points, medium 50, small 100.","Small rocks move fastest; splitting a big one raises the pressure.","You get a short shield after each respawn. Three lives."]'::jsonb, 100000),
  (7, 'Space Invaders', 'space-invaders', 'Hold the line against a descending alien formation. They march faster as their numbers fall, and each wave arrives quicker and angrier than the last.', 'Retro', 'Hard', 4.7, 10240, NULL, NULL, '{"move":"Left / Right, mouse, or drag","fire":"Space / click / tap (hold to auto-fire)","pause":"P or Esc"}'::jsonb, '["Aliens in the back rows are worth more: 40, 30, 20, 10 points.","Your shots can intercept incoming alien fire.","The game ends if the formation reaches your cannon or you lose all three lives."]'::jsonb, 50000),
  (8, 'Pac-Man Style', 'pacman', 'Clear the maze of dots while four ghosts hunt you down. Grab a power pellet to turn the tables and eat them for a rising bonus.', 'Retro', 'Hard', 4.8, 13560, NULL, NULL, '{"move":"Arrow keys / WASD","touch":"Swipe to turn","pause":"P or Esc"}'::jsonb, '["Dots are 10 points, power pellets 50.","Eating ghosts in one power-up scores 200, 400, 800, 1600.","Clear every dot to advance; ghosts get faster each level."]'::jsonb, 100000),
  (12, '2048', '2048', 'Slide the tiles and merge matching numbers. Reach 2048 and then keep going for a high score. Your best is saved on this device.', 'Puzzle', 'Medium', 4.7, 15320, NULL, NULL, '{"move":"Arrow keys / WASD","touch":"Swipe"}'::jsonb, '["Tiles slide as far as they can; equal tiles that collide merge into one.","Every merge adds the new tile''s value to your score.","The game ends when no move is possible."]'::jsonb, 200000),
  (18, 'Chrome Dino', 'dino', 'The offline runner, online. Jump the cacti, duck under the birds, and see how far you can get before the speed becomes unfair.', 'Arcade', 'Medium', 4.5, 12080, NULL, NULL, '{"jump":"Space / Up / tap","duck":"Down / swipe down","pause":"P or Esc"}'::jsonb, '["Score climbs with distance travelled.","Birds appear after 200 points: low ones must be jumped, high ones ducked.","The run gets faster the longer you survive."]'::jsonb, 50000),
  (19, 'Pen Fight', 'pen-fight', 'The school-desk classic in full 3D. Flick your pens into the other side''s and knock them off the edge. Seven pens with their own weight, speed and grip; play the CPU, pass the phone to a friend, or share a room code and play online.', 'Action', 'Medium', 4.9, 0, NULL, NULL, '{"flick":"Drag back from your pen, release","aim":"Left / Right","power":"Up / Down","flick (keys)":"Space","switch pen":"Shift, or tap another pen","pause":"P or Esc"}'::jsonb, '["A pen whose centre crosses the desk edge falls off. Knock theirs off; keep yours on.","Knocking off a pen scores 100, and each extra pen in the same flick scores 50 more.","vs CPU: clear its pens to win the round and earn a bonus. Lose all of yours and it is over.","Every pen is different — heavy pens shove, light pens fly, grippy pens stop short."]'::jsonb, 100000)
ON CONFLICT (slug) DO UPDATE
SET title = EXCLUDED.title,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    difficulty = EXCLUDED.difficulty,
    rating = EXCLUDED.rating,
    iframe_url = EXCLUDED.iframe_url,
    controls_json = EXCLUDED.controls_json,
    rules_json = EXCLUDED.rules_json,
    max_score = EXCLUDED.max_score,
    updated_at = TIMEZONE('utc'::text, NOW());

-- Keep the identity sequence ahead of the fixed ids above.
SELECT setval(pg_get_serial_sequence('public.games', 'id'), (SELECT MAX(id) FROM public.games));

