export { ClassicSnake } from "./Snake";
export { ClassicPong } from "./Pong";
export { ClassicTetris } from "./Tetris";
export { ClassicFlappyBird } from "./FlappyBird";
export { ClassicBreakout } from "./Breakout";
export { ClassicAsteroids } from "./Asteroids";
export { ClassicSpaceInvaders } from "./SpaceInvaders";
export { ClassicPacman } from "./Pacman";
export { Classic2048 } from "./Game2048";
export { ClassicDino } from "./Dino";
export type { GameProps } from "./types";
